
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: db/development
test:
  <<: *default
  database: db/test
production:
  <<: *default
  database: db/production

#development:
#  <<: *default
#  database: twitter_development#

#test:
#  <<: *default
#  database: twitter_test#
#

#production:
#  <<: *default
#  database: twitter_production
#  username: twitter
#  password: <%= ENV['TWITTER_DATABASE_PASSWORD'] %>
